new: use `wh removesocketbinder` to uninstall the socketbinder if present

diff --git a/whtree/bin/wh b/whtree/bin/wh
--- a/whtree/bin/wh
+++ b/whtree/bin/wh
@@ -562,6 +562,15 @@ HERE
     exit 0
     ;;
 
+  "removesocketbinder")
+    echo "Uninstalling socket binder"
+    if ! sudo launchctl unload /Library/LaunchDaemons/com.b-lex.socket_binder.plist ; then # Also shuts down the process
+      echo "Unload failed" >&2
+    fi
+    sudo rm -f /Library/LaunchDaemons/com.b-lex.socket_binder.plist
+    sudo rm -f /var/run/socket_binder.socket
+    ;;
+
   "mic")
     check_webhare_not_running
 
