improve error detection

diff --git a/whtree/bin/wh b/whtree/bin/wh
--- a/whtree/bin/wh
+++ b/whtree/bin/wh
@@ -250,7 +250,7 @@ setup_for_console() #setup_for_console is invoked when we're starting a major su
 if [[ ! "$INSTR" =~ ^(console|mic|umic|exec|execbuilt|shell|make|finalize-webhare|prepare-whdata)$ ]]; then
   if [ -z "$__WEBHARE_IN_PREPARE_WHDATA" ]; then
     export __WEBHARE_IN_PREPARE_WHDATA=1 #Prevent duplicate/looping invocations. It's easy for wh to refer back to itself during execution
-    "$WEBHARE_DIR/modules/platform/scripts/bootstrap/prepare-whdata.sh"
+    "$WEBHARE_DIR/modules/platform/scripts/bootstrap/prepare-whdata.sh" || die "Cannot prepare whdata"
   fi
 fi
 
